// <auto-generated />
using System;
using EchoProtocol.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EchoProtocol.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260920111342_AddPurchaseInventoryM4014M4015")]
    partial class AddPurchaseInventoryM4014M4015
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EchoProtocol.Api.Entities.InventoryItem", b =>
                {
                    b.Property<Guid>("InventoryItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AcquiredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("PurchaseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ShopItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("InventoryItemId");

                    b.HasIndex("PurchaseId")
                        .IsUnique();

                    b.HasIndex("ShopItemId");

                    b.HasIndex("UserId", "ShopItemId")
                        .IsUnique()
                        .HasDatabaseName("IX_InventoryItems_UserId_ShopItemId");

                    b.ToTable("InventoryItems", (string)null);
                });

            modelBuilder.Entity("EchoProtocol.Api.Entities.MatchAuthorityBinding", b =>
                {
                    b.Property<Guid>("MatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EndedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FusionSessionName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("HostUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LeaseExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MatchId");

                    b.HasIndex("HostUserId");

                    b.HasIndex("FusionSessionName", "Status");

                    b.ToTable("MatchAuthorityBindings", (string)null);
                });

            modelBuilder.Entity("EchoProtocol.Api.Entities.MatchPlayerBinding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("BoundAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DisconnectedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FusionActorNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("JoinProofId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasAlternateKey("MatchId", "UserId")
                        .HasName("AK_MatchPlayerBindings_MatchId_UserId");

                    b.HasIndex("JoinProofId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.HasIndex("MatchId", "FusionActorNumber")
                        .IsUnique();

                    b.ToTable("MatchPlayerBindings", (string)null);
                });

            modelBuilder.Entity("EchoProtocol.Api.Entities.MatchResult", b =>
                {
                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EndedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ObjectiveCompletion")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .IsFixedLength();

                    b.Property<int>("PlayerCount")
                        .HasColumnType("integer");

                    b.Property<string>("RewardStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("SubmittedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SubmittedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("MatchId");

                    b.HasIndex("SubmittedAtUtc");

                    b.HasIndex("SubmittedByUserId");

                    b.ToTable("MatchResults", t =>
                        {
                            t.HasCheckConstraint("CK_MatchResults_DurationSeconds_Range", "\"DurationSeconds\" >= 60 AND \"DurationSeconds\" <= 900");

                            t.HasCheckConstraint("CK_MatchResults_ObjectiveCompletion_Range", "CAST(\"ObjectiveCompletion\" AS NUMERIC) >= 0 AND CAST(\"ObjectiveCompletion\" AS NUMERIC) <= 1");

                            t.HasCheckConstraint("CK_MatchResults_Outcome_Allowed", "\"Outcome\" IN ('WIN', 'LOSE')");

                            t.HasCheckConstraint("CK_MatchResults_PlayerCount_Range", "\"PlayerCount\" >= 1 AND \"PlayerCount\" <= 4");

                            t.HasCheckConstraint("CK_MatchResults_RewardStatus_Allowed", "\"RewardStatus\" IN ('Pending', 'Completed')");

                            t.HasCheckConstraint("CK_MatchResults_Timestamp_Order", "\"EndedAtUtc\" >= \"StartedAtUtc\"");
                        });
                });

            modelBuilder.Entity("EchoProtocol.Api.Entities.MatchResultPlayer", b =>
                {
                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("DetectionCount")
                        .HasColumnType("integer");

                    b.Property<bool>("Disconnected")
                        .HasColumnType("boolean");

                    b.Property<int>("DownedCount")
                        .HasColumnType("integer");

                    b.Property<int>("ObjectiveContribution")
                        .HasColumnType("integer");

                    b.Property<int>("ReviveCount")
                        .HasColumnType("integer");

                    b.Property<bool>("Survived")
                        .HasColumnType("boolean");

                    b.HasKey("MatchId", "UserId");

                    b.ToTable("MatchResultPlayers", t =>
                        {
                            t.HasCheckConstraint("CK_MatchResultPlayers_DetectionCount_NonNegative", "\"DetectionCount\" >= 0");

                            t.HasCheckConstraint("CK_MatchResultPlayers_DownedCount_NonNegative", "\"DownedCount\" >= 0");

                            t.HasCheckConstraint("CK_MatchResultPlayers_ObjectiveContribution_NonNegative", "\"ObjectiveContribution\" >= 0");

                            t.HasCheckConstraint("CK_MatchResultPlayers_ReviveCount_NonNegative", "\"ReviveCount\" >= 0");
                        });
                });

            modelBuilder.Entity("EchoProtocol.Api.Entities.MatchRewardGrant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CurrencyAmount")
                        .HasColumnType("integer");

                    b.Property<long>("ExperiencePointsAwarded")
                        .HasColumnType("bigint");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<string>("PolicyVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProgressionPolicyVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WalletId");

                    b.HasIndex("MatchId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_MatchRewardGrants_MatchId_UserId");

                    b.ToTable("MatchRewardGrants", t =>
                        {
                            t.HasCheckConstraint("CK_MatchRewardGrants_CurrencyAmount_NonNegative", "\"CurrencyAmount\" >= 0");

                            t.HasCheckConstraint("CK_MatchRewardGrants_ExperiencePointsAwarded_NonNegative", "\"ExperiencePointsAwarded\" >= 0");
                        });
                });

            modelBuilder.Entity("EchoProtocol.Api.Entities.PlayerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("ExperiencePoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<int>("Level")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<int>("TotalMatches")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("TotalWins")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_PlayerProfiles_UserId");

                    b.ToTable("PlayerProfiles", t =>
                        {
                            t.HasCheckConstraint("CK_PlayerProfiles_ExperiencePoints_NonNegative", "\"ExperiencePoints\" >= 0");

                            t.HasCheckConstraint("CK_PlayerProfiles_Level_Positive", "\"Level\" >= 1");

                            t.HasCheckConstraint("CK_PlayerProfiles_TotalMatches_NonNegative", "\"TotalMatches\" >= 0");

                            t.HasCheckConstraint("CK_PlayerProfiles_TotalWins_Lte_Matches", "\"TotalWins\" <= \"TotalMatches\"");

                            t.HasCheckConstraint("CK_PlayerProfiles_TotalWins_NonNegative", "\"TotalWins\" >= 0");
                        });
                });

            modelBuilder.Entity("EchoProtocol.Api.Entities.PurchaseTransaction", b =>
                {
                    b.Property<Guid>("PurchaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("PriceAtPurchase")
                        .HasColumnType("integer");

                    b.Property<Guid>("ShopItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WalletTransactionId")
                        .HasColumnType("uuid");

                    b.HasKey("PurchaseId");

                    b.HasIndex("ShopItemId");

                    b.HasIndex("WalletTransactionId")
                        .IsUnique();

                    b.HasIndex("UserId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("IX_PurchaseTransactions_UserId_IdempotencyKey");

                    b.ToTable("PurchaseTransactions", t =>
                        {
                            t.HasCheckConstraint("CK_PurchaseTransactions_PriceAtPurchase_NonNegative", "\"PriceAtPurchase\" >= 0");

                            t.HasCheckConstraint("CK_PurchaseTransactions_Status_Completed", "\"Status\" = 'COMPLETED'");
                        });
                });

            modelBuilder.Entity("EchoProtocol.Api.Entities.ShopItem", b =>
                {
                    b.Property<Guid>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssetReference")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ItemId");

                    b.HasIndex("IsActive", "Category", "ItemName", "ItemId")
                        .HasDatabaseName("IX_ShopItems_Active_Category_Name");

                    b.ToTable("ShopItems", t =>
                        {
                            t.HasCheckConstraint("CK_ShopItems_Price_NonNegative", "\"Price\" >= 0");
                        });
                });

            modelBuilder.Entity("EchoProtocol.Api.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Email");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Username");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("EchoProtocol.Api.Entities.Wallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Balance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_Wallets_UserId");

                    b.ToTable("Wallets", t =>
                        {
                            t.HasCheckConstraint("CK_Wallets_Balance_NonNegative", "\"Balance\" >= 0");
                        });
                });

            modelBuilder.Entity("EchoProtocol.Api.Entities.WalletTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<int>("BalanceAfter")
                        .HasColumnType("integer");

                    b.Property<int>("BalanceBefore")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("ReferenceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ReferenceId");

                    b.HasIndex("WalletId", "Type", "ReferenceId")
                        .IsUnique()
                        .HasDatabaseName("IX_WalletTransactions_WalletId_Type_ReferenceId");

                    b.ToTable("WalletTransactions", t =>
                        {
                            t.HasCheckConstraint("CK_WalletTransactions_Amount_ByType", "(\"Type\" = 'MATCH_REWARD' AND \"Amount\" >= 0) OR (\"Type\" = 'PURCHASE' AND \"Amount\" <= 0)");

                            t.HasCheckConstraint("CK_WalletTransactions_BalanceEquation", "\"BalanceAfter\" = \"BalanceBefore\" + \"Amount\"");

                            t.HasCheckConstraint("CK_WalletTransactions_Balances_NonNegative", "\"BalanceBefore\" >= 0 AND \"BalanceAfter\" >= 0");
                        });
                });

            modelBuilder.Entity("EchoProtocol.Api.Entities.InventoryItem", b =>
                {
                    b.HasOne("EchoProtocol.Api.Entities.PurchaseTransaction", "PurchaseTransaction")
                        .WithOne("InventoryItem")
                        .HasForeignKey("EchoProtocol.Api.Entities.InventoryItem", "PurchaseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EchoProtocol.Api.Entities.ShopItem", "ShopItem")
                        .WithMany("InventoryItems")
                        .HasForeignKey("ShopItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EchoProtocol.Api.Entities.User", "User")
                        .WithMany("InventoryItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PurchaseTransaction");

                    b.Navigation("ShopItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EchoProtocol.Api.Entities.MatchAuthorityBinding", b =>
                {
                    b.HasOne("EchoProtocol.Api.Entities.User", "HostUser")
                        .WithMany()
                        .HasForeignKey("HostUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HostUser");
                });

            modelBuilder.Entity("EchoProtocol.Api.Entities.MatchPlayerBinding", b =>
                {
                    b.HasOne("EchoProtocol.Api.Entities.MatchAuthorityBinding", "Match")
                        .WithMany("Players")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EchoProtocol.Api.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EchoProtocol.Api.Entities.MatchResult", b =>
                {
                    b.HasOne("EchoProtocol.Api.Entities.MatchAuthorityBinding", "Match")
                        .WithOne("Result")
                        .HasForeignKey("EchoProtocol.Api.Entities.MatchResult", "MatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EchoProtocol.Api.Entities.User", "SubmittedByUser")
                        .WithMany()
                        .HasForeignKey("SubmittedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("SubmittedByUser");
                });

            modelBuilder.Entity("EchoProtocol.Api.Entities.MatchResultPlayer", b =>
                {
                    b.HasOne("EchoProtocol.Api.Entities.MatchResult", "MatchResult")
                        .WithMany("Players")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EchoProtocol.Api.Entities.MatchPlayerBinding", "PlayerBinding")
                        .WithOne("ResultPlayer")
                        .HasForeignKey("EchoProtocol.Api.Entities.MatchResultPlayer", "MatchId", "UserId")
                        .HasPrincipalKey("EchoProtocol.Api.Entities.MatchPlayerBinding", "MatchId", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MatchResult");

                    b.Navigation("PlayerBinding");
                });

            modelBuilder.Entity("EchoProtocol.Api.Entities.MatchRewardGrant", b =>
                {
                    b.HasOne("EchoProtocol.Api.Entities.Wallet", "Wallet")
                        .WithMany("MatchRewardGrants")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EchoProtocol.Api.Entities.MatchResultPlayer", "ResultPlayer")
                        .WithOne("RewardGrant")
                        .HasForeignKey("EchoProtocol.Api.Entities.MatchRewardGrant", "MatchId", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ResultPlayer");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("EchoProtocol.Api.Entities.PlayerProfile", b =>
                {
                    b.HasOne("EchoProtocol.Api.Entities.User", "User")
                        .WithOne("PlayerProfile")
                        .HasForeignKey("EchoProtocol.Api.Entities.PlayerProfile", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EchoProtocol.Api.Entities.PurchaseTransaction", b =>
                {
                    b.HasOne("EchoProtocol.Api.Entities.ShopItem", "ShopItem")
                        .WithMany("PurchaseTransactions")
                        .HasForeignKey("ShopItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EchoProtocol.Api.Entities.User", "User")
                        .WithMany("PurchaseTransactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EchoProtocol.Api.Entities.WalletTransaction", "WalletTransaction")
                        .WithOne("PurchaseTransaction")
                        .HasForeignKey("EchoProtocol.Api.Entities.PurchaseTransaction", "WalletTransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ShopItem");

                    b.Navigation("User");

                    b.Navigation("WalletTransaction");
                });

            modelBuilder.Entity("EchoProtocol.Api.Entities.Wallet", b =>
                {
                    b.HasOne("EchoProtocol.Api.Entities.User", "User")
                        .WithOne("Wallet")
                        .HasForeignKey("EchoProtocol.Api.Entities.Wallet", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EchoProtocol.Api.Entities.WalletTransaction", b =>
                {
                    b.HasOne("EchoProtocol.Api.Entities.Wallet", "Wallet")
                        .WithMany("Transactions")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("EchoProtocol.Api.Entities.MatchAuthorityBinding", b =>
                {
                    b.Navigation("Players");

                    b.Navigation("Result");
                });

            modelBuilder.Entity("EchoProtocol.Api.Entities.MatchPlayerBinding", b =>
                {
                    b.Navigation("ResultPlayer");
                });

            modelBuilder.Entity("EchoProtocol.Api.Entities.MatchResult", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("EchoProtocol.Api.Entities.MatchResultPlayer", b =>
                {
                    b.Navigation("RewardGrant");
                });

            modelBuilder.Entity("EchoProtocol.Api.Entities.PurchaseTransaction", b =>
                {
                    b.Navigation("InventoryItem")
                        .IsRequired();
                });

            modelBuilder.Entity("EchoProtocol.Api.Entities.ShopItem", b =>
                {
                    b.Navigation("InventoryItems");

                    b.Navigation("PurchaseTransactions");
                });

            modelBuilder.Entity("EchoProtocol.Api.Entities.User", b =>
                {
                    b.Navigation("InventoryItems");

                    b.Navigation("PlayerProfile");

                    b.Navigation("PurchaseTransactions");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("EchoProtocol.Api.Entities.Wallet", b =>
                {
                    b.Navigation("MatchRewardGrants");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("EchoProtocol.Api.Entities.WalletTransaction", b =>
                {
                    b.Navigation("PurchaseTransaction");
                });
#pragma warning restore 612, 618
        }
    }
}
